In [12]:
import numpy as np
import torch
a = torch.rand((4,4))
idx = torch.tensor([0, 2, 1])
idx_mesh_col, idx_mesh_row = torch.meshgrid(idx, idx)
print(a)
sub_a = a[idx,idx]
print(sub_a)
sub_a = a[idx_mesh_row,idx_mesh_col]
print(sub_a)

tensor([[0.5803, 0.9861, 0.0595, 0.1080],
        [0.7745, 0.9496, 0.2619, 0.0455],
        [0.7472, 0.1649, 0.8204, 0.1740],
        [0.7439, 0.6484, 0.9030, 0.8078]])
tensor([0.5803, 0.8204, 0.9496])
tensor([[0.5803, 0.7472, 0.7745],
        [0.0595, 0.8204, 0.2619],
        [0.9861, 0.1649, 0.9496]])


/home/y_yin/anaconda3/envs/cpsl/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392026823/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [13]:
idx_mesh_row

tensor([[0, 2, 1],
        [0, 2, 1],
        [0, 2, 1]])