In [1]:
import numpy as np
import torch
a = torch.rand((4,4))
idx = torch.tensor([0, 2, 1])
idx_mesh_col, idx_mesh_row = torch.meshgrid(idx, idx)
print(a)
sub_a = a[idx,idx]
print(sub_a)
sub_a = a[idx_mesh_row,idx_mesh_col]
print(sub_a)

tensor([[0.3126, 0.0307, 0.0832, 0.0352],
        [0.2442, 0.6509, 0.6058, 0.2858],
        [0.4861, 0.7679, 0.6305, 0.0835],
        [0.1729, 0.2227, 0.6769, 0.0482]])
tensor([0.3126, 0.6305, 0.6509])
tensor([[0.3126, 0.4861, 0.2442],
        [0.0832, 0.6305, 0.6058],
        [0.0307, 0.7679, 0.6509]])


/home/y_yin/anaconda3/envs/cpsl/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392026823/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [5]:
a = torch.tensor([[0,1],[1,0]])
b = torch.tensor([[0,0],[0,0]])
(a == b).int()

tensor([[1, 0],
        [0, 1]], dtype=torch.int32)